name: GOODEAT Backend Build Test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: 해당 브랜치로 체크아웃
        uses: actions/checkout@v2

      - name: JDK 17로 설정
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: selenium을 위한 드라이버 설치
        run: |
          wget https://chromedriver.storage.googleapis.com/100.0.4896.20//chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          mv chromedriver /usr/local/bin/

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build